In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [29]:
filepath='D:/downloads/3405_6663_bundle_archive/'
filename='tmdb_5000_movies.csv'
data=pd.read_csv(filepath+filename)

data.head(2)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   

                                       homepage     id  \
0                   http://www.avatarmovie.com/  19995   
1  http://disney.go.com/disneypictures/pirates/    285   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500

In [30]:
# 필요로 하는 컬럼만 추출 (다른 데이터 전처리로 표준/정규화 , 문자데이터 형태소분석, 불용어제거, 대/소문자 통일 ..)

data=data[['id','genres','vote_average','vote_count','popularity','title','keywords','overview']]
data['vote_count']

0       11800
1        4500
2        4466
3        9106
4        2124
        ...  
4798      238
4799        5
4800        6
4801        7
4802       16
Name: vote_count, Length: 4803, dtype: int64

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   id            4803 non-null   int64  
 1   genres        4803 non-null   object 
 2   vote_average  4803 non-null   float64
 3   vote_count    4803 non-null   int64  
 4   popularity    4803 non-null   float64
 5   title         4803 non-null   object 
 6   keywords      4803 non-null   object 
 7   overview      4800 non-null   object 
dtypes: float64(2), int64(2), object(4)
memory usage: 300.3+ KB


In [35]:
tmp_m=data['vote_count'].quantile(0.90)
tmp_data=data.copy()[data['vote_count']>=tmp_m]
tmp_data.shape

(481, 8)

In [20]:
tmp_data.head(2)

id                                             genres  vote_average  \
0  19995  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           7.2   
1    285  [{"id": 12, "name": "Adventure"}, {"id": 14, "...           6.9   

   vote_count  popularity                                     title  \
0       11800  150.437577                                    Avatar   
1        4500  139.082615  Pirates of the Caribbean: At World's End   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   

                                            overview  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...

In [21]:
C = tmp_data['vote_average'].mean()
M = tmp_m

(WR) = (v ÷ (v+m)) × R + (m ÷ (v+m)) × C

In [22]:
def weighted_rating(x,m=M,c=C):
    v=x['vote_count']
    R=x['vote_average']
    
    return (v/(v+m)*R) + (m/(m+v)*C)

tmp_data['score'] = tmp_data.apply(weighted_rating,axis=1)
tmp_data.head(2)

id                                             genres  vote_average  \
0  19995  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           7.2   
1    285  [{"id": 12, "name": "Adventure"}, {"id": 14, "...           6.9   

   vote_count  popularity                                     title  \
0       11800  150.437577                                    Avatar   
1        4500  139.082615  Pirates of the Caribbean: At World's End   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   

                                            overview     score  
0  In the 22nd century, a paraplegic Marine is di...  7.168053  
1  Captain Barbossa, long believed to be dead, ha...  6.918271

In [23]:
import ast

listStr = '[1,2,3,4,5]'
listData = ast.literal_eval(listStr)
listData

[1, 2, 3, 4, 5]

In [36]:
tmp_data['genres']=tmp_data['genres'].apply(ast.literal_eval)
tmp_data['keywords']=tmp_data['keywords'].apply(ast.literal_eval)

In [33]:
tmp_data[['genres','keywords']].head(3)

genres  \
0  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...   
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
2  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...   

                                            keywords  
0  [{'id': 1463, 'name': 'culture clash'}, {'id':...  
1  [{'id': 270, 'name': 'ocean'}, {'id': 726, 'na...  
2  [{'id': 470, 'name': 'spy'}, {'id': 818, 'name...

In [37]:
def get_names(element):
    return [info['name'] for info in element]

tmp_data['genres']=tmp_data['genres'].apply(get_names)
tmp_data['keywords']=tmp_data['keywords'].apply(get_names)
tmp_data[['genres','keywords']].head(2)

genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   

                                            keywords  
0  [culture clash, future, space war, space colon...  
1  [ocean, drug abuse, exotic island, east india ...

__내장 eval 함수 : 보안 취약__  
__ast 모듈 literal_eval 함수 : 범위가 제한적인(일반적인 수칙연산 지원 X) 대신 안정적(디렉토리 구조 노출 X, 기본 자료형 지원)__  

In [39]:
def join_names(element):
    return ' '.join(element)

tmp_data['genres']=tmp_data['genres'].apply(join_names)
tmp_data['keywords']=tmp_data['keywords'].apply(join_names)
tmp_data[['genres','keywords']].head(2)

genres  \
0  Action Adventure Fantasy Science Fiction   
1                  Adventure Fantasy Action   

                                            keywords  
0  culture clash future space war space colony so...  
1  ocean drug abuse exotic island east india trad...

In [40]:
tmp_data.to_csv('pre_tmdb_5000_movies.csv',index=False)
print('Done')

Done


컨텐츠(성별,장르,토픽,예산,...etc) 기반 필터링 -> 추천 시스템  
우리는 장르를 이용해서 추천시스템을 만들어보자

In [41]:
#장르(문자열) -> 숫자로 변환 -> 벡터화 작업

from sklearn.feature_extraction.text import *

## __BOW : Bag of words , 문서를 구성하는 모든 단어들에 대해 표시하는 방법__  
  
문서1: 나는 대한민국 사람  
문서2: 나는 미국 사람  
문서3: 나는 중국 사람  
* 코퍼스(corpus, 말뭉치) : {'나는','대한민국','사람','미국','중국'}  
---
__※코퍼스 : 단어(도메인) 사전 --> BOW 는 코퍼스의 부분집합 이라고 생각하면 됨__  
토지소설 -> 원고 -> 토지 코퍼스:토지 소설에 등장하는 단어들  
태백산맥 소설 -> 원고 -> 태백산맥 단어들 중에는 토지 코퍼스에 있는 단어도 있지만 없는 단어도 존재 (ex. '지리산')  
이럴 경우 _(OOV)_ 라고 함 (Out Of Vocab)  
***
__※BOW : 전체문서{d1,d2,..,dn}를 구성하는 단어장(vocabulary,{t1,t2,..,tm})을 만든 다음,__  
__각각의 문서(n개)에 대해 단어장에 있는 각각의 단어가 문서 내에 포함되어 있는지 여부를 표시하는 방법__  


In [44]:
from sklearn.feature_extraction import DictVectorizer
# DictVectorizer 단어의 빈도정보가 담긴 딕셔너리로 부터 BOW 벡터 생성
v=DictVectorizer(sparse=False)
D=[{'A':1,'B':2},{'B':3,'C':1}] # 단어의 빈도 정보가 담긴 딕셔너리 , 2개의 문서 , 3개의 단어
x=v.fit_transform(D)
x

array([[1., 2., 0.],
       [0., 3., 1.]])

* Dense matrix : 요소에 0 이 거의 없는 행렬  
* Sparse matrix : 요소에 0 이 많이 있는 행렬 

In [45]:
v.feature_names_

['A', 'B', 'C']

In [46]:
v.transform({'C':4,'D':2}) # 함수 내부 딕셔너리를 v 변수에 저장된 벡터화 방식으로 변환(bow)

array([[0., 0., 4.]])

CountVectorizer  
문서->단어 토큰 리스트->단어 출현 빈도 -> bow 벡터로 변환\

In [50]:
corpus=[ # 해당 도메인에 대한 관련 문서들의 집합
    'This is the first document',
    'This is the second second document',
    'And the third one',
    'The last document'
]

cv = CountVectorizer()
cv.fit(corpus)
print(cv.vocabulary_) # 0~9 까지 총 10개의 단어로 구성
print(cv.transform(corpus).toarray())

{'this': 9, 'is': 3, 'the': 7, 'first': 2, 'document': 1, 'second': 6, 'and': 0, 'third': 8, 'one': 5, 'last': 4}
[[0 1 1 1 0 0 0 1 0 1]
 [0 1 0 1 0 0 2 1 0 1]
 [1 0 0 0 0 1 0 1 1 0]
 [0 1 0 0 1 0 0 1 0 0]]


In [52]:
corpus=[ # 해당 도메인에 대한 관련 문서들의 집합
    'This is the first document',
    'This is the second second document',
    'And the third one',
    'The last document'
]

cv2=CountVectorizer(stop_words=['is','the'])
# stop-_words : 불용어() , 리스트로 전달
cv2.fit(corpus)
print(cv2.vocabulary_) # 0~9 까지 총 10개의 단어로 구성
print(cv2.transform(corpus).toarray())

{'this': 7, 'first': 2, 'document': 1, 'second': 5, 'and': 0, 'third': 6, 'one': 4, 'last': 3}
[[0 1 1 0 0 0 0 1]
 [0 1 0 0 0 2 0 1]
 [1 0 0 0 1 0 1 0]
 [0 1 0 1 0 0 0 0]]


In [53]:
cv=CountVectorizer(stop_words='english')
cv.fit(corpus)
cv.vocabulary_

{'document': 0, 'second': 1}

In [55]:
cv.get_stop_words()

frozenset({'a',
           'about',
           'above',
           'across',
           'after',
           'afterwards',
           'again',
           'against',
           'all',
           'almost',
           'alone',
           'along',
           'already',
           'also',
           'although',
           'always',
           'am',
           'among',
           'amongst',
           'amoungst',
           'amount',
           'an',
           'and',
           'another',
           'any',
           'anyhow',
           'anyone',
           'anything',
           'anyway',
           'anywhere',
           'are',
           'around',
           'as',
           'at',
           'back',
           'be',
           'became',
           'because',
           'become',
           'becomes',
           'becoming',
           'been',
           'before',
           'beforehand',
           'behind',
           'being',
           'below',
           'beside',
           'besides'

In [57]:
cv=CountVectorizer(analyzer='char') # 형태소 분석 : 각 글자마다
cv.fit(corpus)
cv.vocabulary_

{'t': 14,
 'h': 6,
 'i': 7,
 's': 13,
 ' ': 0,
 'e': 4,
 'f': 5,
 'r': 12,
 'd': 3,
 'o': 11,
 'c': 2,
 'u': 15,
 'm': 9,
 'n': 10,
 'a': 1,
 'l': 8}

In [58]:
cv=CountVectorizer(token_pattern='t\w+') # 정규식 활용으로 토큰 사전 생성
cv.fit(corpus)
cv.vocabulary_

{'this': 2, 'the': 0, 'third': 1}

In [ ]:
#n-gram (Word2Vec): 단어의 크기
# 1(모노) 그램 : 토큰 하나만 단어 , 2(바이) 그램 : 두개의 토큰을 하나의 단어로 사용
# This is the first document -> 2-그램으로 표현
# This is, is the, the first, first document

In [60]:
cv=CountVectorizer(ngram_range=(1,2)) # 정규식 활용으로 토큰 사전 생성 1~2 그램 범위 전부 출력
cv.fit(corpus)
cv.vocabulary_

{'this': 20,
 'is': 5,
 'the': 13,
 'first': 3,
 'document': 2,
 'this is': 21,
 'is the': 6,
 'the first': 14,
 'first document': 4,
 'second': 10,
 'the second': 16,
 'second second': 12,
 'second document': 11,
 'and': 0,
 'third': 18,
 'one': 9,
 'and the': 1,
 'the third': 17,
 'third one': 19,
 'last': 7,
 'the last': 15,
 'last document': 8}

In [61]:
cv=CountVectorizer(min_df=2) # 빈도수 범위 지정
cv.fit(corpus)
cv.vocabulary_

{'this': 3, 'is': 1, 'the': 2, 'document': 0}

In [62]:
cv.transform(corpus).toarray().sum(axis=0)
# 각 단어별로 빈도수 출력

array([3, 2, 4, 2], dtype=int64)

# 종합

In [65]:
# 1.fit_transform 함수를 이용한 장르 벡터화
print(tmp_data.head(2))
count_vector = CountVectorizer(ngram_range=(1,3))
c_vector_genres = count_vector.fit_transform(tmp_data['genres'])
print(c_vector_genres.toarray())
print(c_vector_genres.shape)

      id                                    genres  vote_average  vote_count  \
0  19995  Action Adventure Fantasy Science Fiction           7.2       11800   
1    285                  Adventure Fantasy Action           6.9        4500   

   popularity                                     title  \
0  150.437577                                    Avatar   
1  139.082615  Pirates of the Caribbean: At World's End   

                                            keywords  \
0  culture clash future space war space colony so...   
1  ocean drug abuse exotic island east india trad...   

                                            overview  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...  
[[1 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(481, 364)


In [66]:
# 2.fit&transform 함수를 이용한 장르 벡터화
count_vector2 = CountVectorizer(ngram_range=(1,3))
count_vector2.fit(tmp_data['genres'])
count_vector2.get_feature_names()

['action',
 'action adventure',
 'action adventure animation',
 'action adventure comedy',
 'action adventure crime',
 'action adventure fantasy',
 'action adventure science',
 'action adventure thriller',
 'action adventure war',
 'action adventure western',
 'action comedy',
 'action comedy crime',
 'action comedy drama',
 'action comedy family',
 'action comedy science',
 'action crime',
 'action crime drama',
 'action crime mystery',
 'action crime thriller',
 'action drama',
 'action drama adventure',
 'action drama fantasy',
 'action drama history',
 'action drama horror',
 'action drama mystery',
 'action drama science',
 'action drama thriller',
 'action family',
 'action family fantasy',
 'action family romance',
 'action fantasy',
 'action fantasy comedy',
 'action horror',
 'action mystery',
 'action mystery science',
 'action mystery thriller',
 'action romance',
 'action science',
 'action science fiction',
 'action thriller',
 'action thriller adventure',
 'action thrille