In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

데이터 재구호화 : pivit -> pivot_table , stack/unstack , melt , crosstab 등  
crosstab : 요인별로 교차분석 -> 행,열 요인 기준별로 빈도수 -> 도수분포표 , 교차 테이블 생성

In [6]:
data = pd.DataFrame({
    'id':['id1','id1','id1','id2','id2','id3'],
    'f1':['a','a','a','b','b','b'],
    'f2':['d','d','d','c','c','d']
})
data

id f1 f2
0  id1  a  d
1  id1  a  d
2  id1  a  d
3  id2  b  c
4  id2  b  c
5  id3  b  d

In [7]:
pd.crosstab(data.id,data.f2)

f2   c  d
id       
id1  0  3
id2  2  0
id3  0  1

In [8]:
# 다중 라벨
pd.crosstab(data.id,[data.f1,data.f2])

f1   a  b   
f2   d  c  d
id          
id1  3  0  0
id2  0  2  0
id3  0  0  1

In [9]:
pd.crosstab(data.id,[data.f1,data.f2],rownames=['id_num'],colnames=['col1','col2'])

col1    a  b   
col2    d  c  d
id_num         
id1     3  0  0
id2     0  2  0
id3     0  0  1

In [11]:
ser = pd.Series([*range(5)])
ser

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [12]:
ser[ser>=ser.mean()]

2    2
3    3
4    4
dtype: int64

In [19]:
ser = pd.Series([*range(5)],index=list('abcde'))
ser

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [20]:
ser[['b','d']]

b    1
d    3
dtype: int64

In [22]:
ser.loc[['b','d']]

b    1
d    3
dtype: int64

In [25]:
df = pd.DataFrame({
    'c1':[0,1,2,3],
    'c2':[4,5,6,7],
    'c3':[8,9,10,np.nan]},
    index=['r1','r2','r3','r4']
)
df

c1  c2    c3
r1   0   4   8.0
r2   1   5   9.0
r3   2   6  10.0
r4   3   7   NaN

# 오후

In [26]:
arr = np.array(range(1,6))

In [27]:
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [28]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [30]:
np.log1p(arr)

array([0.69314718, 1.09861229, 1.38629436, 1.60943791, 1.79175947])

In [31]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
np.ravel(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
# order option
print(np.ravel(x,order='C')) # 가로 ?
print(np.ravel(x,order='F')) # 세로 ?

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  4  8  1  5  9  2  6 10  3  7 11]


In [37]:
# 배열 연결
a = np.array([1,2,3])
b = np.array([4,5,6])

In [41]:
# 좌우 연결
print(np.r_[a,b])
print(np.hstack([a,b]))
print(np.concatenate([a,b]))

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [48]:
# 상하 연결
print(np.r_[[a],[b]])
print(np.vstack([a,b]))
print(np.concatenate([[a],[b]]))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [50]:
a = np.array([[0,1],[2,3]])
b = np.array([[2,3],[4,5]])
np.concatenate([a,b],axis=0)

array([[0, 1],
       [2, 3],
       [2, 3],
       [4, 5]])