In [1]:
import pandas as pd
import numpy as np
visited=pd.read_csv("survey_visited.csv")
survey=pd.read_csv("survey_survey.csv")

In [2]:
visited

ident   site       dated
0    619   DR-1  1927-02-08
1    622   DR-1  1927-02-10
2    734   DR-3  1939-01-07
3    735   DR-3  1930-01-12
4    751   DR-3  1930-02-26
5    752   DR-3         NaN
6    837  MSK-4  1932-01-14
7    844   DR-1  1932-03-22

In [3]:
survey

taken person quant  reading
0     619   dyer   rad     9.82
1     619   dyer   sal     0.13
2     622   dyer   rad     7.80
3     622   dyer   sal     0.09
4     734     pb   rad     8.41
5     734   lake   sal     0.05
6     734     pb  temp   -21.50
7     735     pb   rad     7.22
8     735    NaN   sal     0.06
9     735    NaN  temp   -26.00
10    751     pb   rad     4.35
11    751     pb  temp   -18.50
12    751   lake   sal     0.10
13    752   lake   rad     2.19
14    752   lake   sal     0.09
15    752   lake  temp   -16.00
16    752    roe   sal    41.60
17    837   lake   rad     1.46
18    837   lake   sal     0.21
19    837    roe   sal    22.50
20    844    roe   rad    11.25

In [5]:
vs=visited.merge(survey, left_on='ident', right_on='taken')
vs

ident   site       dated  taken person quant  reading
0     619   DR-1  1927-02-08    619   dyer   rad     9.82
1     619   DR-1  1927-02-08    619   dyer   sal     0.13
2     622   DR-1  1927-02-10    622   dyer   rad     7.80
3     622   DR-1  1927-02-10    622   dyer   sal     0.09
4     734   DR-3  1939-01-07    734     pb   rad     8.41
5     734   DR-3  1939-01-07    734   lake   sal     0.05
6     734   DR-3  1939-01-07    734     pb  temp   -21.50
7     735   DR-3  1930-01-12    735     pb   rad     7.22
8     735   DR-3  1930-01-12    735    NaN   sal     0.06
9     735   DR-3  1930-01-12    735    NaN  temp   -26.00
10    751   DR-3  1930-02-26    751     pb   rad     4.35
11    751   DR-3  1930-02-26    751     pb  temp   -18.50
12    751   DR-3  1930-02-26    751   lake   sal     0.10
13    752   DR-3         NaN    752   lake   rad     2.19
14    752   DR-3         NaN    752   lake   sal     0.09
15    752   DR-3         NaN    752   lake  temp   -16.00
16    752   DR-3         NaN    752    roe   sal    41.60
17    837  MSK-4  1932-01-14    837   lake   rad     1.46
18    837  MSK-4  1932-01-14    837   lake   sal     0.21
19    837  MSK-4  1932-01-14    837    roe   sal    22.50
20    844   DR-1  1932-03-22    844    roe   rad    11.25

In [6]:
num=pd.Series({'dog':4, 'amoeba':np.nan})
print(num)

# 사과바구니 : 0개
# 사과바구니 : 2개
# nan의 의미는 '사과바구니' 자체가 없음


dog       4.0
amoeba    NaN
dtype: float64


In [12]:
gapminder.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   country    1704 non-null   object 
 1   continent  1704 non-null   object 
 2   year       1704 non-null   int64  
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64  
 5   gdpPercap  1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB


In [13]:
#데이터 -> 그룹화 -> 그룹단위 연산
gapminder=pd.read_csv("gapminder.tsv",sep="\t")
gapminder
print(gapminder.groupby(['country'])['pop'].mean())
print("="*50)
print(gapminder.groupby(['country'])['pop'].max())
print("="*50)
print(gapminder.groupby(['continent'])['gdpPercap'].mean())
#1.582372e+07 = 1.582372 * 10의 7승 = 15823720

country
Afghanistan           1.582372e+07
Albania               2.580249e+06
Algeria               1.987541e+07
Angola                7.309390e+06
Argentina             2.860224e+07
                          ...     
Vietnam               5.456857e+07
West Bank and Gaza    1.848606e+06
Yemen, Rep.           1.084319e+07
Zambia                6.353805e+06
Zimbabwe              7.641966e+06
Name: pop, Length: 142, dtype: float64
country
Afghanistan           31889923
Albania                3600523
Algeria               33333216
Angola                12420476
Argentina             40301927
                        ...   
Vietnam               85262356
West Bank and Gaza     4018332
Yemen, Rep.           22211743
Zambia                11746035
Zimbabwe              12311143
Name: pop, Length: 142, dtype: int64
continent
Africa       2193.754578
Americas     7136.110356
Asia         7902.150428
Europe      14469.475533
Oceania     18621.609223
Name: gdpPercap, dtype: float64


In [16]:
#각 연도별로 그룹화를 한 다음, 그룹단위로 기대수명의 평균을 구하시오.
life_exp=gapminder.groupby(['year'])['lifeExp'].mean()
life_exp

year
1952    49.057620
1957    51.507401
1962    53.609249
1967    55.678290
1972    57.647386
1977    59.570157
1982    61.533197
1987    63.212613
1992    64.160338
1997    65.014676
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64

In [20]:
life_exp.iloc[10]
life_exp.iloc[-2]
life_exp.loc[2002]

65.69492253521126

In [29]:
#life_exp.loc[range(2000,2008),] 지원이 안됨
life_exp.loc[2000:2010,]

print(life_exp.index)
life_exp[life_exp.index>2000]

Int64Index([1952, 1957, 1962, 1967, 1972, 1977, 1982, 1987, 1992, 1997, 2002,
            2007],
           dtype='int64', name='year')


year
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64

In [39]:
ebola=pd.read_csv("country_timeseries.csv")
ebola
#ebola 의 전체 컬럼명을 확인
ebola.columns
len(ebola.columns)
ebola.info()
ebola.count()
ebola.shape #(122, 18)
ebola.shape[0] #122
numMissing=ebola.shape[0] - ebola.count() #스칼라(브로드캐스팅) - 시리즈 = 누락값 개수


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Date                 122 non-null    object 
 1   Day                  122 non-null    int64  
 2   Cases_Guinea         93 non-null     float64
 3   Cases_Liberia        83 non-null     float64
 4   Cases_SierraLeone    87 non-null     float64
 5   Cases_Nigeria        38 non-null     float64
 6   Cases_Senegal        25 non-null     float64
 7   Cases_UnitedStates   18 non-null     float64
 8   Cases_Spain          16 non-null     float64
 9   Cases_Mali           12 non-null     float64
 10  Deaths_Guinea        92 non-null     float64
 11  Deaths_Liberia       81 non-null     float64
 12  Deaths_SierraLeone   87 non-null     float64
 13  Deaths_Nigeria       38 non-null     float64
 14  Deaths_Senegal       22 non-null     float64
 15  Deaths_UnitedStates  18 non-null     flo

Date                     0
Day                      0
Cases_Guinea            29
Cases_Liberia           39
Cases_SierraLeone       35
Cases_Nigeria           84
Cases_Senegal           97
Cases_UnitedStates     104
Cases_Spain            106
Cases_Mali             110
Deaths_Guinea           30
Deaths_Liberia          41
Deaths_SierraLeone      35
Deaths_Nigeria          84
Deaths_Senegal         100
Deaths_UnitedStates    104
Deaths_Spain           106
Deaths_Mali            110
dtype: int64

In [45]:
ebola.isnull().sum() #ebola.isnull().sum(axis=0), 열(컬럼) 단위로 결측값 개수

ebola.isnull().sum(axis=1) #행 단위로 결측값 개수

0      12
1      12
2      10
3      14
4      10
       ..
117    10
118    14
119    14
120    14
121    14
Length: 122, dtype: int64

In [47]:
ebola.isnull().sum() #컬럼 단위 합계
ebola.isnull().sum().sum() #컬럼 단위 합계의 합계(1214?전체 데이터 결측값 개수)

1214

In [52]:
ebola
#누락값을 0으로 대체하세요
ebola.fillna(0)
#누락값을 이전(윗쪽 셀) 값으로 대체하세요
ebola.fillna(method='ffill')
#누락값을 선형적인 값으로 대체하세요
ebola.interpolate()

Date  Day  Cases_Guinea  Cases_Liberia  Cases_SierraLeone  \
0      1/5/2015  289        2776.0            NaN            10030.0   
1      1/4/2015  288        2775.0            NaN             9780.0   
2      1/3/2015  287        2769.0         8166.0             9722.0   
3      1/2/2015  286        2749.5         8157.0             9677.5   
4    12/31/2014  284        2730.0         8115.0             9633.0   
..          ...  ...           ...            ...                ...   
117   3/27/2014    5         103.0            8.0                6.0   
118   3/26/2014    4          86.0            8.0                6.0   
119   3/25/2014    3          86.0            8.0                6.0   
120   3/24/2014    2          86.0            8.0                6.0   
121   3/22/2014    0          49.0            8.0                6.0   

     Cases_Nigeria  Cases_Senegal  Cases_UnitedStates  Cases_Spain  \
0              NaN            NaN                 NaN          NaN   
1              NaN            NaN                 NaN          NaN   
2              NaN            NaN                 NaN          NaN   
3              NaN            NaN                 NaN          NaN   
4              NaN            NaN                 NaN          NaN   
..             ...            ...                 ...          ...   
117            0.0            1.0                 1.0          1.0   
118            0.0            1.0                 1.0          1.0   
119            0.0            1.0                 1.0          1.0   
120            0.0            1.0                 1.0          1.0   
121            0.0            1.0                 1.0          1.0   

     Cases_Mali  Deaths_Guinea  Deaths_Liberia  Deaths_SierraLeone  \
0           NaN         1786.0             NaN              2977.0   
1           NaN         1781.0             NaN              2943.0   
2           NaN         1767.0          3496.0              2915.0   
3           NaN         1753.0          3496.0              2871.0   
4           NaN         1739.0          3471.0              2827.0   
..          ...            ...             ...                 ...   
117         1.0           66.0             6.0                 5.0   
118         1.0           62.0             6.0                 5.0   
119         1.0           60.0             6.0                 5.0   
120         1.0           59.0             6.0                 5.0   
121         1.0           29.0             6.0                 5.0   

     Deaths_Nigeria  Deaths_Senegal  Deaths_UnitedStates  Deaths_Spain  \
0               NaN             NaN                  NaN           NaN   
1               NaN             NaN                  NaN           NaN   
2               NaN             NaN                  NaN           NaN   
3               NaN             NaN                  NaN           NaN   
4               NaN             NaN                  NaN           NaN   
..              ...             ...                  ...           ...   
117             0.0             0.0                  0.0           1.0   
118             0.0             0.0                  0.0           1.0   
119             0.0             0.0                  0.0           1.0   
120             0.0             0.0                  0.0           1.0   
121             0.0             0.0                  0.0           1.0   

     Deaths_Mali  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
4            NaN  
..           ...  
117          1.0  
118          1.0  
119          1.0  
120          1.0  
121          1.0  

[122 rows x 18 columns]

In [56]:
ebola.dropna() #ebola.dropna(axis=0) 같음
#결측값이 있는 모든 행 삭제하시오

ebola.dropna(axis=1)
#결측값이 있는 모든 열 삭제하시오

Date  Day
0      1/5/2015  289
1      1/4/2015  288
2      1/3/2015  287
3      1/2/2015  286
4    12/31/2014  284
..          ...  ...
117   3/27/2014    5
118   3/26/2014    4
119   3/25/2014    3
120   3/24/2014    2
121   3/22/2014    0

[122 rows x 2 columns]

In [57]:
ebola.columns

Index(['Date', 'Day', 'Cases_Guinea', 'Cases_Liberia', 'Cases_SierraLeone',
       'Cases_Nigeria', 'Cases_Senegal', 'Cases_UnitedStates', 'Cases_Spain',
       'Cases_Mali', 'Deaths_Guinea', 'Deaths_Liberia', 'Deaths_SierraLeone',
       'Deaths_Nigeria', 'Deaths_Senegal', 'Deaths_UnitedStates',
       'Deaths_Spain', 'Deaths_Mali'],
      dtype='object')

In [59]:
ebola.head()

Date  Day  Cases_Guinea  Cases_Liberia  Cases_SierraLeone  \
0    1/5/2015  289        2776.0            NaN            10030.0   
1    1/4/2015  288        2775.0            NaN             9780.0   
2    1/3/2015  287        2769.0         8166.0             9722.0   
3    1/2/2015  286           NaN         8157.0                NaN   
4  12/31/2014  284        2730.0         8115.0             9633.0   

   Cases_Nigeria  Cases_Senegal  Cases_UnitedStates  Cases_Spain  Cases_Mali  \
0            NaN            NaN                 NaN          NaN         NaN   
1            NaN            NaN                 NaN          NaN         NaN   
2            NaN            NaN                 NaN          NaN         NaN   
3            NaN            NaN                 NaN          NaN         NaN   
4            NaN            NaN                 NaN          NaN         NaN   

   Deaths_Guinea  Deaths_Liberia  Deaths_SierraLeone  Deaths_Nigeria  \
0         1786.0             NaN              2977.0             NaN   
1         1781.0             NaN              2943.0             NaN   
2         1767.0          3496.0              2915.0             NaN   
3            NaN          3496.0                 NaN             NaN   
4         1739.0          3471.0              2827.0             NaN   

   Deaths_Senegal  Deaths_UnitedStates  Deaths_Spain  Deaths_Mali  
0             NaN                  NaN           NaN          NaN  
1             NaN                  NaN           NaN          NaN  
2             NaN                  NaN           NaN          NaN  
3             NaN                  NaN           NaN          NaN  
4             NaN                  NaN           NaN          NaN

In [67]:
ebola.loc[1]
ebola.loc[1,:]
#ebola.loc[1,0:3] 에러
ebola.iloc[1,0:3]
ebola.loc[1,['Date','Day','Cases_Guinea']]
ebola.loc[1,'Date':'Cases_Guinea']

Date            1/4/2015
Day                  288
Cases_Guinea        2775
Name: 1, dtype: object

In [71]:
#Cases_Guinea 열의 전체 합 출력
ebola.Cases_Guinea.sum()
ebola.Cases_Guinea.sum(skipna=True)

84729.0

In [72]:
ebola.Cases_Guinea.sum(skipna=False)

nan

In [76]:
# 데이터 정규화: 각열데이터-각열최소값  / 각열최대값-각열최소값 => 0~1
# 데이터 표준화: 각열데이터-각열평균값 / 각열데이터의 표준편차 

#표준화 작업 : numpy, scipy.stats, sklearn
np.random.randint(30,size=5) # (범위, 난수개수)
data=np.random.randint(30,size=(6,5)) #6행5열

In [77]:
data #행=건수, 열=변수(피처)
#data에 대해 표준화(열 단위): numpy, scipy.stats, sklearn

array([[ 0, 15,  8, 17, 22],
       [19, 26,  6, 29, 28],
       [14, 15,  9,  7,  9],
       [ 7, 24, 26,  4,  7],
       [27, 21, 28,  8, 21],
       [19, 25, 21, 25, 13]])

In [88]:
#numpy로 표준화(각열데이터-각열평균값 / 각열데이터의 표준편차)

#np.mean(data) #전체 평균
#np.mean(data, axis=1)  #각 행 평균

print(np.mean(data, axis=0))#각 열 평균
#print(10 - np.mean(data, axis=0)) #브로드캐스팅
print(data) #6*5
print(data- np.mean(data, axis=0))
#       6*5  -        (5->6*5)

#     data    
#     [[ 0 15  8 17 22]
#  [19 26  6 29 28]
#  [14 15  9  7  9]
#  [ 7 24 26  4  7]
#  [27 21 28  8 21]
#  [19 25 21 25 13]]
    
    
#     *브로드캐스팅(5->6*5)
#     [14.33333333 21.         16.33333333 15.         16.66666667]
#     =>
#     [14.33333333 21.         16.33333333 15.         16.66666667]
#     [14.33333333 21.         16.33333333 15.         16.66666667]
#     [14.33333333 21.         16.33333333 15.         16.66666667]
#     [14.33333333 21.         16.33333333 15.         16.66666667]
#     [14.33333333 21.         16.33333333 15.         16.66666667]
#     [14.33333333 21.         16.33333333 15.         16.66666667]

[14.33333333 21.         16.33333333 15.         16.66666667]
[[ 0 15  8 17 22]
 [19 26  6 29 28]
 [14 15  9  7  9]
 [ 7 24 26  4  7]
 [27 21 28  8 21]
 [19 25 21 25 13]]
[[-14.33333333  -6.          -8.33333333   2.           5.33333333]
 [  4.66666667   5.         -10.33333333  14.          11.33333333]
 [ -0.33333333  -6.          -7.33333333  -8.          -7.66666667]
 [ -7.33333333   3.           9.66666667 -11.          -9.66666667]
 [ 12.66666667   0.          11.66666667  -7.           4.33333333]
 [  4.66666667   4.           4.66666667  10.          -3.66666667]]


In [97]:
#(data- np.mean(data, axis=0)).shape #(6, 5)
np.std(data, axis=0).shape #5개(열 단위)

data_std=(data- np.mean(data, axis=0)) / np.std(data, axis=0) # 5 -> (6,5), 표준화

#ex) 표준화 결과값 : -1.6 의 의미?
print(data) #데이터 0 값이 해당 열의 평균으로부터 왼쪽으로 표준편차의 1.6배만큼
#떨어진 위치에 있다

[[ 0 15  8 17 22]
 [19 26  6 29 28]
 [14 15  9  7  9]
 [ 7 24 26  4  7]
 [27 21 28  8 21]
 [19 25 21 25 13]]


In [92]:
np.std(data) #8.375891329020186, 표준편차
np.std(data, axis=0) #5개(열 단위)

np.std(data, axis=1) #6개(행 단위)

array([7.65767589, 8.54634425, 3.12409987, 9.39361485, 7.12741187,
       4.45421149])

In [98]:
# x1(평소점수) x2(출석율)  y(합격여부)
# 70              0.5        n
# 90              0.9        y
# ...

# 80             0.6         ???




In [99]:
data_std

array([[-1.63108297, -1.33059829, -0.93040366,  0.21199958,  0.70710678],
       [ 0.53105027,  1.10883191, -1.15370054,  1.48399703,  1.50260191],
       [-0.03793216, -1.33059829, -0.81875522, -0.8479983 , -1.016466  ],
       [-0.83450757,  0.66529914,  1.07926824, -1.16599767, -1.28163104],
       [ 1.44142216,  0.        ,  1.30256512, -0.74199852,  0.57452426],
       [ 0.53105027,  0.88706553,  0.52102605,  1.05999788, -0.48613591]])

In [103]:
np.sum(data_std, axis=0)
np.mean(data_std, axis=0)
np.std(data_std, axis=0)

array([1., 1., 1., 1., 1.])

In [104]:
np.var(data_std, axis=0) #분산

array([1., 1., 1., 1., 1.])