In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',    
]

In [3]:
cv = CountVectorizer()

In [4]:
cv.fit_transform(corpus).toarray()

array([[0, 1, 0, 1, 0, 1, 0, 1, 1],
       [0, 0, 1, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 1, 0, 1, 0, 0]], dtype=int64)

In [5]:
cv.vocabulary_

{'you': 7,
 'know': 1,
 'want': 5,
 'your': 8,
 'love': 3,
 'like': 2,
 'what': 6,
 'should': 4,
 'do': 0}

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [7]:
tv = TfidfVectorizer()

In [8]:
tfidf = tv.fit(corpus)

In [9]:
tfidf.transform(corpus).toarray()

array([[0.        , 0.46735098, 0.        , 0.46735098, 0.        ,
        0.46735098, 0.        , 0.35543247, 0.46735098],
       [0.        , 0.        , 0.79596054, 0.        , 0.        ,
        0.        , 0.        , 0.60534851, 0.        ],
       [0.57735027, 0.        , 0.        , 0.        , 0.57735027,
        0.        , 0.57735027, 0.        , 0.        ]])

In [10]:
tv = TfidfVectorizer(analyzer='char')
tv.fit_transform(corpus).toarray()

array([[0.54522682, 0.14041576, 0.        , 0.14041576, 0.        ,
        0.10904536, 0.14041576, 0.10904536, 0.3692597 , 0.43618145,
        0.18462985, 0.        , 0.14041576, 0.21809073, 0.18462985,
        0.28083152, 0.28083152],
       [0.50040087, 0.        , 0.        , 0.32217861, 0.        ,
        0.50040087, 0.32217861, 0.25020043, 0.        , 0.25020043,
        0.        , 0.        , 0.        , 0.25020043, 0.        ,
        0.        , 0.32217861],
       [0.54546812, 0.17559738, 0.4617789 , 0.        , 0.4617789 ,
        0.13636703, 0.        , 0.13636703, 0.        , 0.27273406,
        0.        , 0.23088945, 0.17559738, 0.13636703, 0.        ,
        0.17559738, 0.        ]])

In [11]:
tv = TfidfVectorizer(min_df=2)
tv.fit_transform(corpus).toarray()

array([[1.],
       [1.],
       [0.]])

In [12]:
tv = TfidfVectorizer(ngram_range=(1,2))
tv.fit_transform(corpus).toarray()

array([[0.        , 0.34142622, 0.34142622, 0.        , 0.        ,
        0.34142622, 0.        , 0.        , 0.34142622, 0.34142622,
        0.        , 0.        , 0.25966344, 0.34142622, 0.34142622,
        0.34142622],
       [0.        , 0.        , 0.        , 0.62276601, 0.62276601,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.4736296 , 0.        , 0.        ,
        0.        ],
       [0.4472136 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.4472136 , 0.4472136 , 0.        , 0.        ,
        0.4472136 , 0.4472136 , 0.        , 0.        , 0.        ,
        0.        ]])

In [13]:
import numpy as np
doc1 = np.array([2,3,0,1])
doc2 = np.array([1,2,3,1])
doc3 = np.array([2,1,2,2])

In [14]:
docInput = np.array([1,1,0,1])

In [23]:
docs = [doc1,doc2,doc3]

for doc in docs:
    dist = np.sqrt(np.square(np.abs(docInput - doc)).sum())
    print(f'입력 문서와 {doc} 사이 거리 : ',dist)

입력 문서와 [2 3 0 1] 사이 거리 :  2.23606797749979
입력 문서와 [1 2 3 1] 사이 거리 :  3.1622776601683795
입력 문서와 [2 1 2 2] 사이 거리 :  2.449489742783178


__자카드 유사도?__

J(문서1,문서2) = (doc1 ∩ doc2) / (doc1 + doc2)  
- 교집합을 합집합으로 나누는 알고리즘  
- 합집합에서 교집합의 비율을 유사도로 사용  
- 0< J < 1 의 값 범위  

In [24]:
doc1 = 'apple banana everyone like likey watch card holder'
doc2 = 'apple banana coupon passport love you'

In [25]:
tok1 = doc1.split()
tok2 = doc2.split()

In [34]:
hab = list(set(tok1)|set(tok2)) # 합집합
hab

['likey',
 'coupon',
 'card',
 'like',
 'passport',
 'holder',
 'everyone',
 'banana',
 'apple',
 'watch',
 'love',
 'you']

In [35]:
gyo = list(set(tok1)&set(tok2)) # 교집합
gyo

['apple', 'banana']

In [36]:
J = len(gyo)/len(hab)
J

0.16666666666666666

In [43]:
from sklearn.metrics.pairwise import cosine_similarity

doc1 = np.array([2,3,0,1])
doc2 = np.array([1,2,3,1])
doc3 = np.array([2,1,2,2])

docInput = np.array([1,1,0,1])

docs = [doc1,doc2,doc3]

for doc in docs:
    cos_sim = cosine_similarity(docInput.reshape(1,-1),doc.reshape(1,-1))
    print(f'입력 문서와 {doc} 코사인 유사도 : ',cos_sim[0])


입력 문서와 [2 3 0 1] 코사인 유사도 :  [0.9258201]
입력 문서와 [1 2 3 1] 코사인 유사도 :  [0.59628479]
입력 문서와 [2 1 2 2] 코사인 유사도 :  [0.80064077]


[https://www.kaggle.com/rounakbanik/the-movies-dataset
](https://www.kaggle.com/rounakbanik/the-movies-dataset
)  
실전!  
- 4.5 만 이상의 영화 메타 정보 텍스트를 처리해보자

In [48]:
import pandas as pd  # 대용량 파일을 다룰때는 low_memory 옵션 끄기
movie_meta = pd.read_csv('C:/임시\RData/movies_metadata.csv', low_memory=False)

In [49]:
movie_meta.head(2)

adult                              belongs_to_collection    budget  \
0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   
1  False                                                NaN  65000000   

                                              genres  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   

                               homepage    id    imdb_id original_language  \
0  http://toystory.disney.com/toy-story   862  tt0114709                en   
1                                   NaN  8844  tt0113497                en   

  original_title                                           overview  ...  \
0      Toy Story  Led by Woody, Andy's toys live happily in his ...  ...   
1        Jumanji  When siblings Judy and Peter discover an encha...  ...   

  release_date      revenue runtime  \
0   1995-10-30  373554033.0    81.0   
1   1995-12-15  262797249.0   104.0   

                                    spoken_languages    status  \
0           [{'iso_639_1': 'en', 'name': 'English'}]  Released   
1  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...  Released   

                                     tagline      title  video vote_average  \
0                                        NaN  Toy Story  False          7.7   
1  Roll the dice and unleash the excitement!    Jumanji  False          6.9   

  vote_count  
0     5415.0  
1     2413.0  

[2 rows x 24 columns]

In [50]:
movie_meta['overview'].head(3)

0    Led by Woody, Andy's toys live happily in his ...
1    When siblings Judy and Peter discover an encha...
2    A family wedding reignites the ancient feud be...
Name: overview, dtype: object

__줄거리 기준으로 영화간 유사도 모델링__

In [52]:
import pandas as pd  # 대용량 파일을 다룰때는 low_memory 옵션 끄기
data = pd.read_csv('C:/임시\RData/movies_metadata.csv', low_memory=False)
data = data.head(20000)

In [55]:
data['overview'] = data['overview'].fillna('')

In [57]:
tfidfMat = TfidfVectorizer(stop_words='english')
tfidfMat=tfidfMat.fit_transform(data['overview'])
tfidfMat.shape

(20000, 47487)

In [59]:
print(np.max(tfidfMat[0].toarray()[0]))

0.5036643709879097


In [65]:
# 퀴즈 2 , 0.5036... 에 해당되는 단어 출력

word_index_dict = TfidfVectorizer(stop_words='english').fit(data['overview']).vocabulary_
index_word_dict = sorted(word_index_dict.items(),key=lambda x:x[1])

idx = np.argmax(tfidfMat[0].toarray()[0])
print(f'해당 단어 : ',index_word_dict[idx][0])

해당 단어 :  buzz


In [66]:
from sklearn.metrics.pairwise import linear_kernel
cos_sim = linear_kernel(tfidfMat,tfidfMat)

In [68]:
indices = pd.Series(data.index,index=data.title).drop_duplicates()
indices

title
Toy Story                                                                       0
Jumanji                                                                         1
Grumpier Old Men                                                                2
Waiting to Exhale                                                               3
Father of the Bride Part II                                                     4
                                                                            ...  
Rebellion                                                                   19995
Versailles                                                                  19996
Two in the Wave                                                             19997
Lotte Reiniger: Homage to the Inventor of the Silhouette Film               19998
RKO Production 601: The Making of 'Kong, the Eighth Wonder of the World'    19999
Length: 20000, dtype: int64

In [71]:
indices['Jumanji']

1

In [89]:
# 주만지 영화와 줄거리 코사인 유사도가 가장 높은 
# 20편의 영화제목을 내림차순으로 출력하고자 한다.

title_in = 'Jumanji'

indices = pd.Series(data.index,index=data.title).drop_duplicates()
cos_sim = linear_kernel(tfidfMat,tfidfMat)


top20_idx = pd.Series(cos_sim[indices[title_in]]).sort_values(ascending=False)[1:21].index

print(f'{title_in} 와 가장 유사한 줄거리의 영화 TOP 20 : ')
print(data.title[top20_idx])


Jumanji 와 가장 유사한 줄거리의 영화 TOP 20 : 
6166                       Brainscan
8801                         Quintet
17223                 The Dark Angel
9503                       Word Wars
13601    The Mindscape of Alan Moore
16843                         DeVour
8079                         Masques
6055                Poolhall Junkies
19726                 Wreck-It Ralph
2486                        eXistenZ
10892                     Stay Alive
13711                     Rhinoceros
1506              The Innocent Sleep
9107                         Nirvana
19345                       The Wave
10703                  Grandma's Boy
7749              The Last of Sheila
14166                          Gamer
12726           Battlefield Baseball
15512                Le Pont du Nord
Name: title, dtype: object
